### ISSUE TITLE
App findet keine BLE Geräte

### ISSUE THREAD

**Issue by jango-fx** [genossefloyd/zynchron#2]
die App kompiliert, startet und sendet erfolgreich Dummy Daten per MQTT, aber die Suche nach Bluetoothgeräten bleibt erfolglos.

Keine Fehlermeldungen.

```
Starte /Users/ [...] /input_all.app/Contents/MacOS/input_all...
MqttOutput tries to connect to Broker on  "broker.mqttdashboard.com" : 1883
MqttOutput is running
Scanning for devices...
```

**Comment by genossefloyd** [comment]
Auf anderem MacBook Air getestet und funktioniert auch. Fehler vermutlich bedingt durch fehlende Unterstützung durch Hardware
